server:
  port: 9991
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    database: 0
    host: chaoge.com
    port: 6379
    timeout: 6000
    #password: 123456
    jedis:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 2
        max-wait: 4000